Add coordinates for remarqued statistic points
Sibyx/phpGPX pull request #64
Opened 2023-02-20 10:37 UTC by nono303

https://github.com/Sibyx/phpGPX/issues/63

2023-07-11 14:37 UTC, Sibyx commented
@nono303 can you please have a look?

2023-07-13 05:56 UTC, nono303 commented
Hi @Sibyx 
Can't see why Merging is blocked ( as i only add new properties. and didn't have permission to approve.
only think I view is a "false" deletion in /src/phpGPX/Models/Stats.php l.95<>119.
I'll try reorder changes to see if it allow merging

2023-07-13 06:00 UTC, nono303 reviewed
No breaking changes

2023-07-13 06:00 UTC, nono303 commented
> didn't have permission to approve  

![image](https://github.com/Sibyx/phpGPX/assets/2869665/8268cf4f-b518-4c2d-9013-b3c1c6e515cc)

2023-07-13 09:20 UTC, Sibyx commented
@nono303 I am the only one who can approve the MR. But please respond to my question in the code review. Thank you :)

2023-07-13 09:25 UTC, nono303 commented
hmmmm... that's why I didn't understand 'cause I didn't have any question to answer in code review :)
![image](https://github.com/Sibyx/phpGPX/assets/2869665/3180ff86-e780-4b43-9628-e9e3ac2f361d)
So what's your question ?

2023-07-13 09:27 UTC, Sibyx requested changes

2023-07-13 09:27 UTC, Sibyx commented on src/phpGPX/Models/Route.php
> +				$this->stats->minAltitudeCoords = ["lat" => $this->points[$i]->latitude, "lng" => $this->points[$i]->longitude];
Hello, are you sure about the `$i` index use in this code block?

2023-07-13 09:28 UTC, Sibyx commented
I'm so sorry, @nono303. I forgot to submit the review and it was pending on my side all this time.

2023-07-13 09:36 UTC, nono303 commented on src/phpGPX/Models/Route.php
> +				$this->stats->minAltitudeCoords = ["lat" => $this->points[$i]->latitude, "lng" => $this->points[$i]->longitude];
hi @Sibyx, you're right, it's $p !
fixed in https://github.com/Sibyx/phpGPX/pull/64/commits/5abd3c33aa15ec746836e6e5e15a26f72b8a4d56

2023-07-13 10:40 UTC, Sibyx approved these changes
Looks good. May i ask you to mention it somewhere in the docs or README? I know the current state of the docs is not that good. I hope I will resolved someday in the long planned 2.x release (feel free to help if you have time for that).

2023-07-13 13:01 UTC, nono303 commented
> Looks good @nono303. May i ask you to mention it somewhere in the docs or README? I know the current state of the docs is not that good. I hope I will resolved someday in the long planned 2.x release (feel free to help if you have time for that).

I'll do it next week

2023-07-13 13:23 UTC, Sibyx commented
> > Looks good @nono303. May i ask you to mention it somewhere in the docs or README? I know the current state of the docs is not that good. I hope I will resolved someday in the long planned 2.x release (feel free to help if you have time for that).
> 
> I'll do it next week

Sure, take your time as you need. Thank you for your contribution :)

2023-07-19 14:08 UTC, nono303 commented
Hi @Sibyx ,
Let you review [063adf1](https://github.com/Sibyx/phpGPX/pull/64/commits/063adf12f6baddda577fdb479bfcc9585361fdd5) and tag it as 1.2.2 if OK for you

2023-07-19 17:04 UTC, Sibyx commented
Love it, thank you very much for your contribution!

2023-07-19 17:05 UTC, merged